-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(OFF.SALES_AMOUNT) * P.PRICE AS SALES
FROM OFFLINE_SALE AS OFF
LEFT JOIN PRODUCT AS P ON OFF.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE