-- 코드를 작성해주세요
WITH BIGGEST AS(
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS BIGGEST_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (B.BIGGEST_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM ECOLI_DATA AS E
JOIN BIGGEST AS B ON YEAR(DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV