-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS FN ON F.FISH_TYPE = FN.FISH_TYPE
WHERE LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO AS F2
    WHERE F.FISH_TYPE = F2.FISH_TYPE
) AND LENGTH > 10
ORDER BY ID